# Docker Compose overrides for development
name: confirmator-dev
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
    # folder. Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/app:cached
      - /app/node_modules

    ports:
      - '3030:3030'
      - '3031:3031'

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    restart: 'no'

    user: 1000:1000

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  mongodb:
    image: mongo
    restart: 'no'
    working_dir: /app
    volumes:
      # Persistent data volume
      - mongodb_data:/data
      # Init script
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
